version: "3.8"

services:
  angular-frontend:
    image: sanchaljustgrow/ang-springs-frontend:latest
    container_name: angular-frontend
    ports:
      - "8080:80"
    env_file:
      - .env
    command: >
      /bin/sh -c "sed -i 's|\\$API_URL|${API_URL}|g' /usr/share/nginx/html/assets/env.js &&
                  nginx -g 'daemon off;'"
