version: "3.9"

services:
  # ======================
  # MySQL Database
  # ======================
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
    ports:
      - "3307:3306"        # MySQL exposed on local port 3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # ======================
  # Spring Boot Backend
  # ======================
  backend:
    image: sanchaljustgrow/ang-spring-backend:latest
    container_name: ang-spring-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blogdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - app-network

  # ======================
  # Angular Frontend
  # ======================
  frontend:
    image: sanchaljustgrow/ang-spring-frontend:latest
    container_name: ang-spring-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"        # Angular app accessible via localhost:4200
    environment:
      # Backend accessible within Docker network as 'ang-spring-backend'
      API_BASE_URL: http://ang-spring-backend:8080
    networks:
      - app-network

# ======================
# Volumes and Networks
# ======================
volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
