services:
  angular-frontend:
    image: sanchaljustgrow/ang-springs-frontend:latest
    container_name: angular-frontend
    ports:
      - "8080:80"
    env_file:
      - .env.dev
    command: >
      sh -c "envsubst < /usr/share/nginx/html/assets/env.template.js >
      /usr/share/nginx/html/assets/env.js &&
      nginx -g 'daemon off;'"
