version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
    ports:
      - "3307:3306"

  backend:
    build:
      context: ../ang-spring/backend
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blogdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  frontend:
    build:
      context: ../ang-spring/frontend
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "4200:4200"
    depends_on:
      - backend
