version: "3.9"
services:
  backend:
    image: sanchaljustgrow/ang-spring-backend:latest
    container_name: ang-spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    restart: always

  frontend:
    image: sanchaljustgrow/ang-spring-frontend:latest
    container_name: ang-spring-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    environment:
      - API_URL=${API_URL:-http://localhost:8080}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    restart: always
