version: "3.8"

services:
  angular-frontend:
    image: sanchaljustgrow/ang-springs-frontend:latest
    container_name: angular-frontend
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
