services:
  real-estate-db:
    image: mysql:8.0
    container_name: real-estate-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  real-estate-backend:
    image: real-estate-backend:latest
    container_name: real-estate-backend
    env_file:
      - .env
    depends_on:
      - real-estate-db
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
