version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      # 👇 This will override the frontend API URL dynamically
      - API_URL=http://localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
